### ISSUE TITLE
Code quality enforcement

### ISSUE THREAD

**Issue by aneeshdurg** [illinois-cs241/wikibook-project#23]
In order to maintain a consistent sense of style/formatting in our tex source, I propose that we use a tool like [texpretty](http://ftp.math.utah.edu/pub/texpretty/) or the [online latex formatter](https://c.albert-thompson.com/latex-pretty/) (if we can find an API for it).

I tried playing around with texpretty and it seems promising, but it doesn't really like some of our macros/embedded code snippets.

**Comment by bhuvy2** [comment]
I'm closing because after looking into it
* Linters are pretty much useless because of the number of exceptions needed
* Most of the above tools are outdated and newer tools do very little like indent code. Maybe this can be a good one-two punch and then keep up with code reviewing but the source shouldn't be too bad.
